use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The Card (Set Deck) Data Model describes the properties of a single card found in a Deck (Set).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CardSetDeck {
    /// The number of this cards in the deck.
    pub count: u32,

    /// If the card is foiled.
    pub is_foil: Option<bool>,

    /// The universal unique identifier (v5) generated by MTGJSON.
    pub uuid: Uuid,
}
