use chrono::NaiveDate;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{identifiers::Identifiers, purchase_urls::PurchaseUrls};

/// Describes a list of properties for a purchase-able product of a Set.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SealedProduct {
    /// A list of identifiers associated to a product.
    pub identifiers: Identifiers,

    /// The name of the product.
    pub name: String,

    /// Links that navigate to websites where the product can be purchased.
    pub purchase_urls: PurchaseUrls,

    /// The release date in ISO 8601 format for the product.
    pub release_date: Option<NaiveDate>,

    /// The universal unique identifier (v5) generated by MTGJSON. Each entry is unique.
    pub uuid: Uuid,
}
